# NickRequest by Thomas Edwards
# Theres only language based stuff to configure here
# Everything else is handled via permissions.

# General Plugin Settings
# Nickname format, Ideal for servers used to Essentials.
# {PREFIX} - Group/Player Prefix (Requires Vault)
# {SUFFIX} - Group/Player Suffix (Requires Vault)
# {GROUP} - Group Name (Requires Vault)
# {NICK} - Players Nickname
nick-format: "{NICK}"

# Messages, Edit to suit - UNIMPLEMENTED
messages:
   approved: "Your Nickname '$nick' was approved and applied!"
   denied: "Your Nickname '$nick' was approved and wasn't applied!"
   waiting: "Your Nickname '$nick' is still awaiting approval."