# NickRequest by Thomas Edwards
# Theres only language based stuff to configure here
# Everything else is handled via permissions.

# General Plugin Settings
# Nickname format, Ideal for servers used to Essentials.
# {PREFIX} - Group/Player Prefix (Requires Vault)
# {SUFFIX} - Group/Player Suffix (Requires Vault)
# {GROUP} - Group Name (Requires Vault)
# {NICK} - Players Nickname
nick-format: "{NICK}"

# Database settings
# For standard flatfile (Pre v0.8) use 'file'
# For MySQL use 'mysql' and fill in the details
# In the event the plugin fails to connect to MySQL it will disable it's self
# Until you have fixed the issue
# To import from file or sql to the opposite format set "import" to the database
# you wish to import. If you're migrating to MySQL set import to "file"
# When you've imported data you MUST set import to "none" otherwise your
# data may get overwritten each time the plugin loads. :(
database:
  type: 'file'
  host: 127.0.0.1
  port: 3306
  username: "example"
  password: "example"
  prefix: "nreq_"
  database: "nicknamerequest"
  import: "none"

# General configuration

# Automatically restrict new users from requesting a nickname
# Requires someone to manually unrestrict them, useful for donation stores
# where a user may buy nickname access
auto-restrict: false
# How long are they restricted from requesting a nickname for?
# In seconds, when this time is up from them first joining they'll be able to request
# a nickname, putting 0 disables this and restricts them indefinitely.
auto-restrict-time: 0

# Nickname cooldown, this uses the restriction feature
# How long in seconds does the player have to wait until they can request another nickname?
# Set to 0 to disable. The cooldown is used after a nickname has been accepted/denied
accept-cooldown: 0
deny-cooldown: 0

# Max nickname length (Can be bypassed by the API)
max-length: 32

# Message Strings, change to suit!
# Certain strings will have access to certain placeholders
# {NICK} and {USERNAME} are common ones
messages:
   info-requested: "&aNickname requested!"

   info-self-no-nick: "&bYou don't currently have a nickname."
   info-self-current-nick: "&bYour current nickname is &r{NICK}"
   info-self-no-request: "&bYou don't currently have a nickname request."
   info-self-current-request: "&bYou've requested the nickname '&r&r{NICK}&b'"
   info-self-not-restricted: "&aYou're not currently restricted from requesting a nickname"
   info-self-perm-restricted: "&cYou're currently restricted from requesting a nickname indefinitely."
   info-self-timed-restricted: "&cYou're currently restricted from requesting a nickname for {TIME} seconds."

   info-other-no-nick: "&b{USERNAME} doesn't currently have a nickname."
   info-other-current-nick: "&b{USERNAME} has the nickname &r{NICK}"
   info-other-no-request: "&b{USERNAME} doesn't currently have a nickname request."
   info-other-current-request: "&b{USERNAME} has requested the nickname '&r{$NICK}&r&b'"
   info-other-not-restricted: "&a{USERNAME} isn't currently restricted from requesting a nickname."
   info-other-perm-restricted: "&c{USERNAME} is currently restricted from requesting a nickname indefinitely."
   info-other-timed-restricted: "&c{USERNAME} is currently restricted from requesting a nickname for {TIME} seconds."

   info-other-denied: "&cYou're only able to check your own info!"

   standard-invalid-user: "&cNo such user!"
   standard-user-only-cmd: "This is a user ONLY command!"