name: NicknameRequest
main: com.infermc.nicknamerequest.Main
description: Nickname Requester - Easy nicknaming for users and staff.
author: Thomas Edwards (TMFKSOFT/MajesticFudgie)
softdepend: [Vault,StaleAPI]
version: 0.3
commands:
   nick:
     description: Nickname Control, Check request status, Request a nickname, Disable your nickname.
     usage: 'Usage: /nick set|request|accept|deny|list|cancel|status|remove'
     aliases: [nickname,nk]