name: NicknameRequest
main: com.infermc.nicknamerequest.NicknameRequest
description: Nickname Requester - Easy nicknaming for users and staff.
author: Thomas Burnett-Taylor (TMFKSOFT/MajesticFudgie)
softdepend: [Vault,StaleAPI]
version: 0.11 (11th June 2022)
api-version: 1.18
commands:
   nick:
     description: Nickname Control, Check request status, Request a nickname, Disable your nickname.
     usage: 'Usage: /nick set|request|accept|deny|list|cancel|status|remove|restrict|unrestrict|info'
     aliases: [nickname,nk]